<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />     
    <?php echo $this->headLink()->appendStylesheet('/css/layout.css') ?>
    <?php echo $this->extjs() ?>
    <?php echo $this->functions() ?>
    <?php echo $this->menu() ?>
    <?php echo $this->dynamicResources() ?>    
    <?php echo $this->headTitle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headStyle() ?>
</head>
<body>
    <?php echo $this->basicinfo() ?>
    <div id="layout">    
        <div id="layout-header">
            <img src="/images/header.jpg" />
        </div>
        <div id="layout-menu"></div>        
        <div id="slot1"></div>
        <div id="slot2">
            <?php
            echo $this->layout()->content;        
            ?>
        </div>
    </div>
</body>
</html>
