<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />     
    <?php echo $this->headLink()->appendStylesheet('/css/layout.css') ?>
    <?php echo $this->extjs() ?>
    <?php echo $this->functions() ?>
    <?php echo $this->menu() ?>
    <?php echo $this->dynamicResources() ?>    
    <?php echo $this->headTitle() ?>
    <?php echo $this->headScript() ?>
    <?php echo $this->headStyle() ?>
</head>
<body>
    <?php echo $this->basicinfo() ?>
    <div id="layout">
    <?php
        $module = Zend_Controller_Front::getInstance()->getRequest()->getModuleName();        
        $controller = Zend_Controller_Front::getInstance()->getRequest()->getControllerName();                
        $view = Zend_Controller_Front::getInstance()->getRequest()->getActionName();
        $noheader = $module.'_'.$controller."_".$view;
        if($noheader != 'default_index_index'){
    ?>
    <div id="layout-header">
        <img src="/images/header.jpg" />
    </div>
        <div id="layout-menu"></div>
        <?php
        }
        ?>
    <div id="slot1">
        <?php
        echo $this->layout()->content;        
        ?>
    </div>
    </div>
</body>
</html>